[pytest]   # заголовок секции
python_files = test_*.py  # в каких файлах искать тесты
python_classes = Test*    # в нутри каких классов искать тестовые методы
python_functions = test_*  # какие функции и методы считать тестами